
Training Begins
Traceback (most recent call last):
  File "C:/Users/Breeze/Desktop/AdvancedUnet/train/train_main.py", line 134, in <module>
    run()
  File "C:/Users/Breeze/Desktop/AdvancedUnet/train/train_main.py", line 130, in run
    train(base_net, train_loader, test_loader)
  File "C:/Users/Breeze/Desktop/AdvancedUnet/train/train_main.py", line 63, in train
    for i, data in enumerate(train_loader, 0):
  File "C:\Users\Breeze\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\Breeze\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "C:\Users\Breeze\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "C:\Users\Breeze\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Breeze\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Breeze\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Breeze\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Breeze\Desktop\AdvancedUnet\loaders\cache_loader.py", line 47, in __getitem__
    or_image = self.load_image('%s_real_image.%s' % (main_path, self.extension[root_id]))
  File "C:\Users\Breeze\Desktop\AdvancedUnet\loaders\cache_loader.py", line 81, in load_image
    image = np.array(Image.open(path))
  File "C:\Users\Breeze\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2891, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../data/train/demo_text_vm_ds/train/480_real_image.jpg'